### PR TITLE
Fixes and improvements required for TR1 runtime

### PR DESCRIPTION
**Pull request by janvrany**

### CODE REVIEW

**Comment by shingarov** [comment]
I forgot: What did we want to do with this?  Shall we simply stop spending our energy on it?

**Comment by janvrany** [comment]
I'd say we bite the bullet, "simply stop spending our energy on it" and (try to) move over to libgdbs. This will likely reveal a number of (different) bugs but I'm willing to fix them. 

That said, I'd still merge this PR. The code has been written already and as of now, this is the only way to run MTR experiment from summer 2023.

**Comment by shingarov** [comment]
The reason I started looking at SmallRSP again over the weekend, is because I haven't found a way to continue experiments with below-RSP-level debug protocols, namely Microwatt DMI and perhaps even the old PPC debug (see #3), with libgdbs.  It's like "if you want to play with those, you are stuck in non-Smalltalk space e.g. pygdbstub or OpenOCD" and it's kind of no fun.

**Comment by janvrany** [comment]
I see.
I'd say it's a matter of taste. For smalltalker it is clearly more fun to do it "in smalltalk" but as soon as you get beyond experimeting with basic communication stuff and getting to debug something "real" (as real as say U-Boot : - ) I'd think one (well, I at the very least) start appreciate full GDB. But that's my biased view.

**Comment by shingarov** [comment]
Right, debugging U-Boot is exactly what I am doing at this very moment, and my problem is there simply isn't a working full-GDB.  Be it as it may; merging.

**Comment by shingarov** [comment]
Hmm... shall we make `modtalk-revived` the default branch?

**Comment by janvrany** [comment]
> Right, debugging U-Boot is exactly what I am doing at this very moment, and my problem is there simply isn't a working full-GDB.  Be it as it may; merging.

OK, now it gets interesting! I'd like to see.

**Comment by janvrany** [comment]
> Hmm... shall we make modtalk-revived the default branch?

I'd leave it as it is. There's already so much "this works with this branch and not that branch" and who knows what other (historical) stuff this may break.

**Pull request merged**
